#!/usr/bin/env bash
#  ____        _           _ _                  
# / ___|  __ _| | __ _  __| | |_ ___   ___  ___ 
# \___ \ / _` | |/ _` |/ _` | __/ _ \ / _ \/ __|
#  ___) | (_| | | (_| | (_| | || (_) |  __/\__ \
# |____/ \__,_|_|\__,_|\__,_|\__\___/ \___||___/
                                              
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### VARIABLES ####
COLORSCHEME="doom-one"

#### AUTOSTART ####
sxhkd &
picom &
killall nm-applet && nm-applet &
killall volumeicon && volumeicon &
/usr/bin/emacs --daemon &
killall conky && conky -c "$HOME"/.config/conky/xmonad/"$COLORSCHEME"-01.conkyrc
polybar mainbar-bspwm & 
polybar mainbar-bspwm-secondmon &
~/.config/awesome/xrandr.sh &
### Select only ONE of the following four ways to set the wallpaper.
xargs xwallpaper --stretch < ~/.cache/wall &
# ~/.fehbg &
# feh --randomize --bg-fill /usr/share/backgrounds/dtos-backgrounds/* &
# nitrogen --restore &
dunst &
#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord follow=off